local motions = {
	-- basic
	{ mode = "n", lhs = "h", desc = "Move cursor left" },
	{ mode = "n", lhs = "j", desc = "Move cursor down" },
	-- { mode = "n", lhs = "gj", desc = "Move cursor down one screen line" },
	{ mode = "n", lhs = "k", desc = "Move cursor up" },
	-- { mode = "n", lhs = "gk", desc = "Move cursor up one screen line" },
	{ mode = "n", lhs = "l", desc = "Move cursor right" },
	-- wordwise
	{ mode = "n", lhs = "w", desc = "Move to next word beginning" },
	{ mode = "n", lhs = "W", desc = "Move to next WORD beginning" },
	{ mode = "n", lhs = "b", desc = "Move to previous word beginning" },
	{ mode = "n", lhs = "B", desc = "Move to previous WORD beginning" },
	{ mode = "n", lhs = "e", desc = "Move to next word end" },
	{ mode = "n", lhs = "E", desc = "Move to next WORD end" },
	{ mode = "n", lhs = "ge", desc = "Move to previous word end" },
	{ mode = "n", lhs = "gE", desc = "Move to previous WORD end" },
	-- charwise
	{ mode = "n", lhs = "f", desc = "Find character forward (use with character)" },
	{ mode = "n", lhs = "F", desc = "Find character backward (use with character)" },
	{ mode = "n", lhs = "t", desc = "Till character forward (use with character)" },
	{ mode = "n", lhs = "T", desc = "Till character backward (use with character)" },
	{ mode = "n", lhs = ";", desc = "Repeat last f/F/t/T" },
	{ mode = "n", lhs = ",", desc = "Repeat last f/F/t/T in opposite direction" },
	-- endwise
	{ mode = "n", lhs = "0", desc = "Move to beginning of line" },
	{ mode = "n", lhs = "g0", desc = "Move to beginning of screen line" },
	{ mode = "n", lhs = "^", desc = "Move to first non-blank character of line" },
	{ mode = "n", lhs = "g^", desc = "Move to first non-blank character of screen line" },
	{ mode = "n", lhs = "$", desc = "Move to end of line" },
	{ mode = "n", lhs = "g$", desc = "Move to end of screen line" },
	{ mode = "n", lhs = "_", desc = "Move to first non-blank character of line (with count)" },
	{ mode = "n", lhs = "g_", desc = "Move to last non-blank character of line (with count)" },
	-- vertical
	{ mode = "n", lhs = "%", desc = "Move to matching bracket/tag/statement" },
	{ mode = "n", lhs = "}", desc = "Move to next newline" },
	{ mode = "n", lhs = "{", desc = "Move to previous newline" },
	{ mode = "n", lhs = "(", desc = "Move to previous chunk or newline" },
	{ mode = "n", lhs = ")", desc = "Move to next chunk or newline" },
	{ mode = "n", lhs = "gg", desc = "Go to first line" },
	{ mode = "n", lhs = "G", desc = "Go to last line" },
}

local edit_operations = {
	{ mode = "n", lhs = ".", desc = "Repeat last command" },
	{ mode = "n", lhs = "d", desc = "Delete operator (use with motion)" },
	{ mode = "n", lhs = "dd", desc = "Delete line" },
	{ mode = "n", lhs = "D", desc = "Delete to end of line" },
	{ mode = "n", lhs = "c", desc = "Change operator (use with motion)" },
	{ mode = "n", lhs = "cc", desc = "Change line" },
	{ mode = "n", lhs = "C", desc = "Change to end of line" },
	{ mode = "n", lhs = "y", desc = "Yank operator (use with motion)" },
	{ mode = "n", lhs = "yy", desc = "Yank line" },
	{ mode = "n", lhs = "Y", desc = "Yank to end of line" },
	{ mode = "n", lhs = "p", desc = "Put after cursor" },
	{ mode = "n", lhs = "P", desc = "Put before cursor" },
	{ mode = "n", lhs = "u", desc = "Undo" },
	{ mode = "n", lhs = "<C-r>", desc = "Redo" },
	{ mode = "n", lhs = "x", desc = "Delete character" },
	{ mode = "n", lhs = "X", desc = "Delete character before cursor" },
	{ mode = "n", lhs = "r", desc = "Replace character" },
	{ mode = "n", lhs = "J", desc = "Join lines" },
	{ mode = "n", lhs = ">", desc = "Indent operator (use with motion)" },
	{ mode = "n", lhs = ">>", desc = "Indent line" },
	{ mode = "n", lhs = "<", desc = "De-indent operator (use with motion)" },
	{ mode = "n", lhs = "<<", desc = "De-indent line" },
	{ mode = "n", lhs = "=", desc = "Auto-indent operator (use with motion)" },
	{ mode = "n", lhs = "==", desc = "Auto-indent line" },
}

local mode_changes = {
	{ mode = "n", lhs = "i", desc = "Insert before cursor" },
	{ mode = "n", lhs = "I", desc = "Insert at beginning of line" },
	{ mode = "n", lhs = "a", desc = "Append after cursor" },
	{ mode = "n", lhs = "A", desc = "Append at end of line" },
	{ mode = "n", lhs = "o", desc = "Open line below" },
	{ mode = "n", lhs = "O", desc = "Open line above" },
	{ mode = "n", lhs = "v", desc = "Visual mode" },
	{ mode = "n", lhs = "V", desc = "Visual line mode" },
	{ mode = "n", lhs = "<C-v>", desc = "Visual block mode" },
	{ mode = "n", lhs = ":", desc = "Command line" },
	{ mode = "n", lhs = "s", desc = "Substitute character" },
	{ mode = "n", lhs = "S", desc = "Substitute line" },
}

local search = {
	{ mode = "n", lhs = "/", desc = "Search forward" },
	{ mode = "n", lhs = "?", desc = "Search backward" },
	{ mode = "n", lhs = "n", desc = "Next search match" },
	{ mode = "n", lhs = "N", desc = "Previous search match" },
	{ mode = "n", lhs = "*", desc = "Search forward for word under cursor" },
	{ mode = "v", lhs = "*", desc = "Search forward for selection" },
	{ mode = "n", lhs = "#", desc = "Search backward for word under cursor" },
	{ mode = "v", lhs = "#", desc = "Search backward for selection" },
	{ mode = "n", lhs = "g*", desc = "Search forward for partial word under cursor" },
	{ mode = "n", lhs = "g#", desc = "Search backward for partial word under cursor" },
	{ mode = "v", lhs = "#", desc = "Search backward for word under cursor" },
}

local default_text_objects = {
	{ mode = "n", lhs = "aw", desc = "Around word" },
	{ mode = "n", lhs = "iw", desc = "Inside word" },
	{ mode = "n", lhs = "aW", desc = "Around WORD" },
	{ mode = "n", lhs = "iW", desc = "Inside WORD" },
	{ mode = "n", lhs = "ap", desc = "Around paragraph" },
	{ mode = "n", lhs = "ip", desc = "Inside paragraph" },
	{ mode = "n", lhs = "a)", desc = "Around parentheses" },
	{ mode = "n", lhs = "i)", desc = "Inside parentheses" },
	{ mode = "n", lhs = "a]", desc = "Around brackets" },
	{ mode = "n", lhs = "i]", desc = "Inside brackets" },
	{ mode = "n", lhs = "a}", desc = "Around braces" },
	{ mode = "n", lhs = "i}", desc = "Inside braces" },
	{ mode = "n", lhs = 'a"', desc = "Around double quotes" },
	{ mode = "n", lhs = 'i"', desc = "Inside double quotes" },
	{ mode = "n", lhs = "a'", desc = "Around single quotes" },
	{ mode = "n", lhs = "i'", desc = "Inside single quotes" },
	{ mode = "n", lhs = "as", desc = "Around sentence" },
	{ mode = "n", lhs = "is", desc = "Inside sentence" },
}

local navigation = {
	{ mode = "n", lhs = "<C-d>", desc = "Scroll down half a screen" },
	{ mode = "n", lhs = "<C-u>", desc = "Scroll up half a screen" },
	{ mode = "n", lhs = "<C-e>", desc = "Scroll down one line" },
	{ mode = "n", lhs = "<C-y>", desc = "Scroll up one line" },
	{ mode = "n", lhs = "<C-f>", desc = "Scroll down one screen" },
	{ mode = "n", lhs = "<C-b>", desc = "Scroll up one screen" },
	{ mode = "n", lhs = "zz", desc = "Center cursor line in window" },
	{ mode = "n", lhs = "zt", desc = "Move cursor line to top of window" },
	{ mode = "n", lhs = "zb", desc = "Move cursor line to bottom of window" },
	{ mode = "n", lhs = "gf", desc = "Go to file under cursor" },
	{ mode = "n", lhs = "gF", desc = "Go to file:line under cursor" },
	{ mode = "n", lhs = "g;", desc = "Go to older change position" },
	{ mode = "n", lhs = "g,", desc = "Go to newer change position" },
	{ mode = "n", lhs = "gm", desc = "Go to middle of screen (horizontally)" },
	{ mode = "n", lhs = "M", desc = "Go to middle of screen (vertically)" },
	{ mode = "n", lhs = "gM", desc = "Go to middle of screen (vertically and horizontally)" },
	{ mode = "n", lhs = "<C-o>", desc = "Jump to older position in jump list" },
	{ mode = "n", lhs = "<C-i>", desc = "Jump to newer position in jump list" },
	{ mode = "n", lhs = "<C-^>", desc = "Jump to alternate file" },
	{ mode = "n", lhs = "<C-w>h", desc = "Move to left window" },
	{ mode = "n", lhs = "<C-w>j", desc = "Move to lower window" },
	{ mode = "n", lhs = "<C-w>k", desc = "Move to upper window" },
	{ mode = "n", lhs = "<C-w>l", desc = "Move to right window" },
	{ mode = "n", lhs = "[[", desc = "Go to previous section" },
	{ mode = "n", lhs = "]]", desc = "Go to next section" },
}

local insert_mode = {
	{ mode = "i", lhs = "<Esc>", desc = "Exit insert mode" },
	{ mode = "i", lhs = "<C-h>", desc = "Backspace" },
	{ mode = "i", lhs = "<C-u>", desc = "Delete to beginning of line" },
	{ mode = "i", lhs = "<C-w>", desc = "Delete word before cursor" },
	{ mode = "i", lhs = "<C-t>", desc = "Indent line" },
	{ mode = "i", lhs = "<C-d>", desc = "De-indent line" },
	{ mode = "i", lhs = "<C-j>", desc = "New line below" },
	{ mode = "i", lhs = "<C-o>", desc = "Temporarily enter normal mode for single command" },
	{ mode = "i", lhs = "<C-r>", desc = "Insert contents of register (follow with letter of register)" },
}

local marks = {
	{ mode = "n", lhs = "m", desc = "Set mark (follow with letter of register)" },
	{ mode = "n", lhs = "'", desc = "Jump to mark line (follow with letter of register)" },
	{ mode = "n", lhs = "`", desc = "Jump to mark position (follow with letter of register)" },
	{ mode = "n", lhs = "''", desc = "Jump to previous mark line" },
	{ mode = "n", lhs = "``", desc = "Jump to previous mark position" },
	{ mode = "n", lhs = "'.", desc = "Jump to last change line" },
	{ mode = "n", lhs = "`.", desc = "Jump to last change position" },
	{ mode = "n", lhs = "'[", desc = "Jump to start of last change/yank line" },
	{ mode = "n", lhs = "`[", desc = "Jump to start of last change/yank position" },
	{ mode = "n", lhs = "']", desc = "Jump to end of last change/yank line" },
	{ mode = "n", lhs = "`]", desc = "Jump to end of last change/yank position" },
	{ mode = "n", lhs = "'<", desc = "Jump to start of last visual selection line" },
	{ mode = "n", lhs = "`<", desc = "Jump to start of last visual selection position" },
	{ mode = "n", lhs = "'>", desc = "Jump to end of last visual selection line" },
	{ mode = "n", lhs = "`>", desc = "Jump to end of last visual selection position" },
}

local macros_and_registers = {
	{ mode = "n", lhs = "q", desc = "Start recording macro (follow with letter of register)/Stop recording macro" },
	{ mode = "n", lhs = "@", desc = "Execute macro (follow with letter of register)" },
	{ mode = "v", lhs = "@", desc = "Execute macro (follow with letter of register)" },
	{ mode = "n", lhs = "@@", desc = "Repeat last executed macro" },
	{ mode = "n", lhs = '"', desc = "Use register (follow with letter of register)" },
	{ mode = "v", lhs = '"', desc = "Use register (follow with letter of register)" },
}

local folds = {
	{ mode = "n", lhs = "za", desc = "Toggle fold under cursor" },
	{ mode = "n", lhs = "zA", desc = "Toggle all folds under cursor recursively" },
	{ mode = "n", lhs = "zo", desc = "Open fold under cursor" },
	{ mode = "n", lhs = "zO", desc = "Open all folds under cursor recursively" },
	{ mode = "n", lhs = "zc", desc = "Close fold under cursor" },
	{ mode = "n", lhs = "zC", desc = "Close all folds under cursor recursively" },
	{ mode = "n", lhs = "zf", desc = "Create fold (with motion/visual selection)" },
	{ mode = "v", lhs = "zf", desc = "Create fold from selection" },
	{ mode = "n", lhs = "zF", desc = "Create fold for N lines" },
	{ mode = "n", lhs = "zd", desc = "Delete fold under cursor" },
	{ mode = "n", lhs = "zD", desc = "Delete all folds under cursor recursively" },
	{ mode = "n", lhs = "zE", desc = "Eliminate all folds in window" },
	{ mode = "n", lhs = "zi", desc = "Toggle fold enable/disable" },
	{ mode = "n", lhs = "zj", desc = "Move to next fold" },
	{ mode = "n", lhs = "zk", desc = "Move to previous fold" },
	{ mode = "n", lhs = "zm", desc = "Fold more (close one fold level)" },
	{ mode = "n", lhs = "zM", desc = "Close all folds" },
	{ mode = "n", lhs = "zn", desc = "Fold none (disable folding)" },
	{ mode = "n", lhs = "zN", desc = "Fold normal (enable folding)" },
	{ mode = "n", lhs = "zr", desc = "Reduce folding (open one fold level)" },
	{ mode = "n", lhs = "zR", desc = "Open all folds" },
	{ mode = "n", lhs = "zv", desc = "View cursor line (open just enough folds)" },
	{ mode = "n", lhs = "zx", desc = "Update folds" },
	{ mode = "n", lhs = "zX", desc = "Undo manually opened/closed folds" },
	{ mode = "n", lhs = "[z", desc = "Move to start of current open fold" },
	{ mode = "n", lhs = "]z", desc = "Move to end of current open fold" },
}

local visual_mode = {
	{ mode = "v", lhs = "d", desc = "Delete selection" },
	{ mode = "v", lhs = "y", desc = "Yank selection" },
	{ mode = "v", lhs = "c", desc = "Change selection" },
	{ mode = "v", lhs = ">", desc = "Increase indentation of selection" },
	{ mode = "v", lhs = "<", desc = "Decrease indentation of selection" },
	{ mode = "v", lhs = "=", desc = "Auto-indent selection" },
	{ mode = "v", lhs = "~", desc = "Toggle case of selection" },
	{ mode = "v", lhs = "u", desc = "Lower case selection" },
	{ mode = "v", lhs = "U", desc = "Upper case selection" },
}
return {
	mode_changes = mode_changes,
	motions = motions,
	edit_operations = edit_operations,
	default_text_objects = default_text_objects,
	search = search,
	insert_mode = insert_mode,
	visual_mode = visual_mode,
	macros_and_registers = macros_and_registers,
	marks = marks,
	navigation = navigation,
	folds = folds,
}
